import { RandomCar } from './types';

const cars: RandomCar[] = [
  {
    Toyota: [
      'Corolla',
      'Camry',
      'Rav4',
      'Prius',
      'Highlander',
      'Tacoma',
      'Tundra',
      'Sienna',
      'Yaris',
      '4Runner',
    ],
  },
  {
    Honda: [
      'Civic',
      'Accord',
      'CR-V',
      'Pilot',
      'Odyssey',
      'Fit',
      'Ridgeline',
      'HR-V',
      'Insight',
      'Passport',
    ],
  },
  {
    ' Ford': [
      'F-150',
      'Escape',
      'Explorer',
      'Focus',
      'Edge',
      'Mustang',
      'Ranger',
      'Fusion',
      'Expedition',
      'EcoSport',
    ],
  },
  {
    Chevrolet: [
      'Silverado',
      'Equinox',
      'Malibu',
      'Traverse',
      'Tahoe',
      'Camaro',
      'Colorado',
      'Blazer',
      'Suburban',
      'Corvette',
    ],
  },
  {
    ' Volkswagen': [
      'Jetta',
      'Passat',
      'Tiguan',
      'Atlas',
      'Golf',
      'Arteon',
      'ID.4',
      'Taos',
      'Atlas Cross Sport',
      'Touareg',
    ],
  },
  {
    'Mercedes-Benz': [
      'C-Class',
      'E-Class',
      'S-Class',
      'GLC',
      'GLE',
      'GLA',
      'G-Class',
      'A-Class',
      'CLA',
      'GLB',
    ],
  },
  {
    ' BMW': [
      '3 Series',
      '5 Series',
      'X3',
      'X5',
      'X1',
      '7 Series',
      'X7',
      '2 Series',
      '4 Series',
      '8 Series',
    ],
  },
  { ' Audi': ['A4', 'Q5', 'A3', 'Q7', 'Q3', 'A6', 'A5', 'Q8', 'A7', 'e-tron'] },
  {
    Hyundai: [
      'Elantra',
      'Sonata',
      'Tucson',
      'Santa Fe',
      'Kona',
      'Palisade',
      'Venue',
      'Accent',
      'Veloster',
      'Ioniq',
    ],
  },
  {
    Kia: [
      'Sorento',
      'Sportage',
      'Telluride',
      'Soul',
      'Forte',
      'Optima',
      'Stinger',
      'Rio',
      'Cadenza',
      'K5',
    ],
  },
];

export default cars;
